### PR TITLE
PR to make Symata Pkg(3) ready.

### PR DESCRIPTION
**Pull request by goedman**
Still using included version of LambertW.

Items in PR:

1. Added Manifest.toml to ,gitignore
2. Added Project.toml and all required dependencies
3. Updated .travis.yml
4. Minor edit to README

### CODE REVIEW

**Comment by jlapeyre** [comment]
Rob, thanks. I wanted to squeeze your commits into one. I did this, added one more commit and then pushed. But, it did not give you credit. I'm not sure, but I think if I remove my commit and force push then your commit is on top and github gives you credit.

But, I think it's better that you change the PR, squeeze the commits. This will  make this PR history and your contribution more clear. If this is too much of a PITA, I'll just do what I said above: This PR will be closed, but github should show a different contribution coming from you. (This has taken a lot of time for me today, but it's good git practice!)

If you decide to rework the PR, these are things I'd like to change, they are present in the current master branch on github (until I force push an earlier master)

* Put everything in one commit. (squeeze or rebase)

* Remove the blank lines in the .travis.yml . Most packages have no blank lines. (and make sure there is no extra white space)

* Include both the v0.6.3 badge and the v0.7 badge in the README.

* I put v0.4.1-dev instead of v0.4.1 in the Project file.  I don't want to make a tag or release right now.

* Some of your commits are before I released v0.4.0. I used rebase to move them after v0.4.0. I'm not sure how this would work if you squeeze the commits.  But, I'd like to avoid altering the history before v0.4.0.

**Comment by jlapeyre** [comment]
Also, I'd like to hold off on depending on LambertW again. For me, keeping Pkg3 happy with my installed and dev'd packages is extra work, and something I have to try to understand. Since it's not needed now, I'd like to focus on other things. When it's more clear to everyone how Pkg3 works we can change to depending on LambertW.  Thanks again for the help getting up to speed on Pkg3.

**Comment by jlapeyre** [comment]
I reset master locally and on github to the commit before adding your edits.

For reference, the previous master, with your squeezed commits, is now on this branch:
https://github.com/jlapeyre/Symata.jl/tree/goedman-CI-rel

I *think* that if I squeeze the two commits on this branch,  change the author to you, and merge with master, then the commit is under your name on the contributors page.  Or, you can rework this PR.

**Comment by goedman** [comment]
John, I'm not at all concerned about getting credit for any of my help. I would be concerned though if I have caused you extra work. That was not my intention. Please pick the route that is least work for you.

Benefitting from a package like Symata takes some effort/time-investment and I fully expect it will be used for projects that are going to be published (e.g. the Vianello example and examples in chapter 7 of the NMfE.jl package) and Pkg(3) hopefully will provide that reproducibility. But none of that is time critical.

**Comment by jlapeyre** [comment]
Ok, good, I just don't want assume I  can put someone's under my name.  I chose to continue working on your PR because it was a good git workout; I did some new things!

**Comment by jlapeyre** [comment]
I'm excited to hear about the possible publication. Let me know if you need help or have suggestions.

**Comment by jlapeyre** [comment]
Ok, this was the fastest way for me to commit:
https://github.com/jlapeyre/Symata.jl/commits/master

**Pull request closed without merging**
